### ISSUE TITLE
About onnx export

### ISSUE THREAD

**Issue by memofemanon** [maliangzhibi/MixformerV2-onnx#1]
Hi, Will you consider sharing the onnx export code? I was looking for onnx export method for mixformerv2 while I came across your work.
Since I'm working on the model with images of input size 288, your shared models won't work in my case. I tried to write my own but had some problem dealing with the multiple inputs and the original code:(

**Comment by memofemanon** [comment]
Managed to export the 288/128/128 model with pred_scores and pred_bbox as outputs. In case anyone needs it: https://drive.google.com/file/d/1nIRJaAM4o9rCAjtafdbd1ceP7yakJKqv/view?usp=sharing

**Comment by cococolorful** [comment]
> Managed to export the 288/188/188 model with pred_scores and pred_bbox as outputs. In case anyone needs it: https://drive.google.com/file/d/1nIRJaAM4o9rCAjtafdbd1ceP7yakJKqv/view?usp=sharing

@yujunsun110 Hi, would you give me some advice on how to export `mixformer2_vit_online` to onnx.
The following code could **not** be exported successfully
```
# self.network(self.template, self.online_template, search, softmax=True, run_score_head=True)
onnx_program = torch.onnx.dynamo_export(self.network, self.template, self.online_template, search, softmax=True, run_score_head=True )

```
