### ISSUE TITLE
What is the reference for ONNX models?

### ISSUE THREAD

**Issue by fbasatemur** [maliangzhibi/MixformerV2-onnx#2]
Hi, in the Mixformerv2 study, base and small models are mentioned. What is the torch reference model for your ONNX model ?

**Comment by shuai-dian** [comment]
@fbasatemur Have you solved it already?

**Comment by fbasatemur** [comment]
I solved it, The Mixformer v2 small model was used, which can be inferred from the input size of the onnx model, thank you.

**Comment by fbasatemur** [comment]
> @fbasatemur Have you solved it already?

I solved it, The Mixformer v2 small model was used, which can be inferred from the input size of the onnx model, thank you.

**Comment by shuai-dian** [comment]
@fbasatemur How did you export it?When I exported the model, how to deal with the set_online part, and I could not export the whole model where score prediction was exported, so I disassembled the model and exported three parts: backbone, box and score. Can you share the exported code with me?
